services:
  - type: web
    name: helpdesk
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn helpdesk.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: helpdesk-db
          property: connectionString
  - type: pserv
    name: helpdesk-db
    env: docker
    plan: free
    image:
      url: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: helpdesk_db
